name: financeai_manager
description: Application intelligente de gestion financière personnelle avec assistant IA
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Navigation
  cupertino_icons: ^1.0.2
  go_router: ^12.1.3
  
  # State Management
  provider: ^6.1.1
  
  # Database & Storage
  supabase_flutter: ^2.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Authentication
  local_auth: ^2.1.6
  crypto: ^3.0.3
  
  # Charts & Graphs
  fl_chart: ^0.65.0
  
  # HTTP & API
  http: ^1.1.0
  dio: ^5.3.2
  
  # Utils
  intl: ^0.18.1
  uuid: ^4.1.0
  shared_preferences: ^2.2.2
  
  # Notifications
  flutter_local_notifications: ^16.1.0
  
  # File handling
  path_provider: ^2.1.1
  csv: ^5.0.2
  share_plus: ^7.2.1
  
  # Animations & UI Effects
  flutter_spinkit: ^5.2.0
  shimmer: ^3.0.0
  confetti: ^0.7.0
  lottie: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

# Configuration pour flutter_launcher_icons
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/financeai_logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icons/financeai_logo.png"
  windows:
    generate: true
    image_path: "assets/icons/financeai_logo.png"
  macos:
    generate: true
    image_path: "assets/icons/financeai_logo.png"
